# Generated by Django 4.1.7 on 2023-04-26 07:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0002_rename_title_expenses_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expenses",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Expense",
                "verbose_name_plural": "Expenses",
            },
        ),
    ]
